{
    "Service": "/gapscanNEW/Services/SampleServiceV2.service",
    "DefiningRequests": [{
        "Name": "Products",
        "Query": "Products"
    }],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnSuccess": "/gapscanNEW/Actions/Service/InitializeOfflineSuccessMessage.action",
    "OnFailure": "/gapscanNEW/Actions/Service/InitializeOfflineFailureMessage.action"
}